# cloudbuild.yaml
steps:
- name: node:14.15.5-alpine3.13
  entrypoint: npm
  args: ["install"]
- name: node:14.15.5-alpine3.13
  entrypoint: npm
  args: ["run", "build"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'cloudrunservice'
    - '--image'
    - 'us-docker.pkg.dev/cloudrun/container/test-cg'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
timeout: "1600s"
