# cloudbuild.yaml
steps:
- name: node:14.15.5-alpine3.13
  entrypoint: npm
  args: ["install", "-g", "@angular/cli"]
- name: node:14.15.5-alpine3.13
  entrypoint: ng
  args: ["build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
